# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certify < Formula
  desc "Certify is an easy-to-use certificate manager and can be used as an alternative to OpenSSL. With Certify you can create your own private CA (Certificate Authority) and issue certificates with your own CA"
  homepage "https://github.com/nothinux/homebrew-tools"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nothinux/certify/releases/download/v1.8.0/certify_1.8.0_darwin_amd64.tar.gz"
      sha256 "873f212bb3a227427732ec0c33ac736f31381036fdf826c58308da4525dd157b"

      def install
        bin.install "certify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nothinux/certify/releases/download/v1.8.0/certify_1.8.0_darwin_arm64.tar.gz"
      sha256 "84e3fef33e8ea5e690c30bb52c5b3d7c8b129748659abb04985ee1af33c46b98"

      def install
        bin.install "certify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nothinux/certify/releases/download/v1.8.0/certify_1.8.0_linux_armv6.tar.gz"
      sha256 "a43b485dcc97ef8b917c68edd33bc3205d12e0d586ff1f055cf4c4d7d858555e"

      def install
        bin.install "certify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nothinux/certify/releases/download/v1.8.0/certify_1.8.0_linux_amd64.tar.gz"
      sha256 "3c0547ce1179a26e0b8589ae31544f62249411fc28748cf6b02eb39b308bf3dd"

      def install
        bin.install "certify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nothinux/certify/releases/download/v1.8.0/certify_1.8.0_linux_arm64.tar.gz"
      sha256 "c7a13ffbcf27ad8205d87d229e5a1471a26c2b47157ba978663fff995eff8a67"

      def install
        bin.install "certify"
      end
    end
  end
end
