# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KubeResourceStatus < Formula
  desc ":crab: kube resource-status is a tool that provide kubernetes cluster resource i"
  homepage "https://github.com/nothinux/kube-resource-status"
  url "https://github.com/nothinux/kube-resource-status/archive/v0.1.0.tar.gz", using: CurlDownloadStrategy
  sha256 "73e580539e81cd20ee6faa22e0f5f8c652fdbc935727b94e12efe2147e0c234e"

  on_macos do
    on_intel do
      url "https://github.com/nothinux/kube-resource-status/releases/download/v0.1.0/kube-resource-status-0.1.0-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f557b2ce205cc0f7758413f029c9a829734129c9a15a2acd7f5b592486192f15"
    end

    on_arm do
      url "https://github.com/nothinux/kube-resource-status/releases/download/v0.1.0/kube-resource-status-0.1.0-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "047f2091d650451ebfd823e01375a78ebc14399680895e772e9d7c05052cd7c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nothinux/kube-resource-status/releases/download/v0.1.0/kube-resource-status-0.1.0-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "961306f92d126be83f8a3e55352e105c2537ef91d2590decf34b2fbe0fab1e2d"
    end
  end

  def install
    bin.install "kubectl-resource_status"
  end
end
